name: verily_server
description: Verily action verification server.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  google_generative_ai: ^0.4.6
  http: any
  logging: ^1.3.0
  serverpod: 3.3.1
  serverpod_auth_idp_server: 3.3.1
  solana_kit: ^0.2.1
  verily_core:
    path: ../verily_core

dev_dependencies:
  serverpod_test: 3.3.1
  test: ^1.25.5
  verily_lints:
    path: ../verily_lints

serverpod:
  scripts:
    start: dart bin/main.dart --apply-migrations
    flutter_build:
      posix: |
        cd ../verily_app
        flutter build web --base-href /app/ --wasm --output ../verily_server/web/app
