apiServer:
  port: 8080
  publicHost: api.verily.fun
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: insights.verily.fun
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: app.verily.fun
  publicPort: 443
  publicScheme: https

database:
  host: database.private-production.verily.fun
  port: 5432
  name: serverpod
  user: postgres
  requireSsl: true

redis:
  enabled: false
  host: redis.private-production.verily.fun
  port: 6379

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: false
