[global]
show_hash = true
upgrade_only = true
target = ".eget/bin"
all = true

["knope-dev/knope"]
asset_filters = [".tgz"]
tag = "knope/v0.22.3"

["pulumi/pulumi"]
asset_filters = [".tar.gz", "^.sig"]
tag = "v3.223.0"

["pulumi/esc"]
asset_filters = [".tar.gz"]
tag = "v0.22.0"

["pnpm/pnpm"]
asset_filters = ["^linuxstatic"]
tag = "v10.30.2"
